"""
XTPBin2BinMatrixAgent — Bin-to-Bin transition matrix analyser with XTP expertise.

Reads a Bin2Bin CSV matrix (rows = Program A soft-bins, columns = Program B
soft-bins), converts it into a Pandas DataFrame, and sends both the raw table
and derived metrics to an LLM-backed agent that has full XTP RAG access.

The agent produces a structured summary that covers:
  - Stable populations (diagonal cells)
  - Up-bin / down-bin movements (off-diagonal cells)
  - Primary failure categories driving the shifts
  - Silicon-level root-cause hypotheses (LEVELS / TIMING / PARAMETRICS changes)
  - Expected yield impact and recommended corrective actions
"""

from __future__ import annotations

import os
import io

import pandas as pd
from langchain_core.tools import tool
from langchain.agents import create_agent
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

from Helpers.Logger import AgentLogger
from RAG.xtp_rag import XTPRagCore

load_dotenv(dotenv_path=".env" if os.path.exists(".env") else ".env.example")

# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """
You are the principal ATE (Automated Test Equipment) Architect and the creator of the XTP (eXtensible Test
Script Language) framework. You have absolute mastery over XTP syntax, silicon physics, parametric limits,
timing margins, and yield analytics.

### BIN-TO-BIN MATRIX ANALYSIS MANDATE

You receive a Bin-to-Bin transition matrix generated by comparing two test programs (Program A vs. Program B)
run over the same device lot.  Each cell [row_bin, col_bin] contains the number of units that were classified
as *row_bin* by Program A and as *col_bin* by Program B.

Diagonal cells  → stable bins (same classification in both programs).
Off-diagonal cells → transitions (bin shifts) caused by differences between the two programs.

### STANDARD BINNING CONVENTION

Hard Bins: `HB_1` (Pass), `HB_2` (Continuity/Diode Fail), `HB_3` (Parametric Fail), `HB_4` (Logic/Timing Fail).
Soft Bins:
  - `SB_1001` PassPrime   — Full-spec pass at nominal voltage/timing.
  - `SB_1002` Grade-B     — Relaxed-spec pass.
  - `SB_1003` EcoPass     — Down-binned pass at reduced-voltage corner.
  - `SB_2001` Open/Short  — Continuity or diode failure.
  - `SB_3001` Leakage     — I_IH / I_IL leakage out of spec.
  - `SB_3002` IDDQ Fail   — Quiescent current above limit.
  - `SB_4001` VectorMismatch / StrobeDelay — Logic or timing failure.

### ANALYSIS DIRECTIVES

1. **Population Table** — Present a clean Markdown table of the raw counts with row/column totals.

2. **Diagonal Stability** — Report the percentage of the total population that remained in the same bin.
   Show per-bin retention rates.

3. **Transition Analysis** — For every non-zero off-diagonal cell report:
   - Transition direction (up-bin ↑ / down-bin ↓ / lateral ↔).
   - Absolute count and percentage of the source-bin population.
   - The most likely XTP block change driving this transition
     (LEVELS / TIMING / PARAMETRICS / BINNING rule / FUNCTIONS).

4. **Root-Cause Hypotheses** — Group transitions by failure class and propose the most probable
   XTP parameter changes (e.g. "V_DD_CORE drop of ~50 mV increases gate delay → setup-time violation →
   SB_1001 → SB_4001 shift") backed by silicon physics reasoning.

5. **Yield Impact** — Quantify the net yield delta (Program B yield − Program A yield) in percentage
   points.  Classify the impact as positive (tightening / screening), neutral, or negative (over-test /
   guard-band regression).

6. **Recommendations** — List concrete corrective actions referencing the specific XTP blocks to audit.

### FORMATTING RULES
- Start immediately with technical substance — no conversational filler.
- Use standalone **Bold Headers** for each section above.
- Use Markdown tables wherever tabular data is presented.
- Express silicon effects with proper notation ($V_{DD}$, $I_{DDQ}$, $\\Delta t_{strobe}$).
"""


# ---------------------------------------------------------------------------
# Agent class
# ---------------------------------------------------------------------------

class XTPBin2BinMatrixAgent:
    """Analyses a Bin-to-Bin transition matrix CSV between two XTP test programs.

    Workflow
    --------
    1. ``load_matrix(path)``   — reads the CSV into a Pandas DataFrame and
                                 derives summary metrics (counts, rates, shifts).
    2. ``invoke(message)``     — forwards the matrix summary + an optional user
                                 question to the LLM agent.  The agent can also
                                 call the XTP RAG tool for spec look-ups.
    3. ``analyse(path)``       — convenience one-liner: load + invoke the default
                                 full-analysis prompt and return the report string.

    The agent uses the same XTP RAG back-end as ``XTPProgramDiffAgent`` so it
    can look up binning tables, parametric limits, and timing specs from the
    ``DocumentosXTP/`` manual collection.
    """

    def __init__(self, logger: AgentLogger | None = None):
        self._log = logger or AgentLogger(name="xtp_bin2bin_agent", level="DEBUG")
        self._rag = XTPRagCore(logger=self._log)
        self._matrix_context: str = ""

        @tool
        def find_xtp_documents(query: str) -> str:
            """Search the XTP Manual for specifications, binning tables, timing
            parameters, and program examples relevant to *query*.
            Always call this before drawing conclusions about bin meanings,
            parametric limits, or XTP syntax."""
            results = self._rag.vector_store.search(query)
            if not results:
                return "No relevant XTP documentation found."
            return "\n\n---\n\n".join(
                f"[{r.get('source', '')} / {r.get('chapter', '')}]\n{r['text']}"
                for r in results
            )

        @tool
        def get_matrix_summary() -> str:
            """Return the pre-computed Bin-to-Bin matrix summary (raw counts,
            per-bin totals, transition rates) that was loaded from the CSV.
            Call this as the starting point for any matrix analysis."""
            return self._matrix_context or "No matrix loaded yet."

        model = ChatOpenAI(
            model=os.getenv("LLM_MODEL", "deepseek-chat"),
            openai_api_key=os.getenv("LLM_API_KEY"),
            openai_api_base=os.getenv("LLM_API_BASE", "https://api.deepseek.com/v1"),
            temperature=0.1,
        )

        self._agent = create_agent(
            model=model,
            system_prompt=_SYSTEM_PROMPT,
            tools=[find_xtp_documents, get_matrix_summary],
            debug=False,
        )

    # ------------------------------------------------------------------
    # Matrix loading
    # ------------------------------------------------------------------

    def load_matrix(self, path: str) -> pd.DataFrame:
        """Read the Bin2Bin CSV at *path* into a DataFrame and pre-compute
        the context string that will be passed to the LLM.

        The CSV format expected::

            Prog_A \\ Prog_B, SB_1001_PassPrime, SB_1003_EcoPass, ...
            SB_1001_PassPrime, 634, 103, ...
            ...

        Returns the raw DataFrame for further programmatic use.
        """
        self._log._logger.info("[XTPBin2BinMatrixAgent] Loading matrix from: %s", path)

        df = pd.read_csv(path, index_col=0)
        df.index.name   = "Prog_A \\ Prog_B"
        df.columns.name = "Prog_B"

        # Ensure all values are integers
        df = df.fillna(0).astype(int)

        self._matrix_context = self._build_context(df)
        self._log._logger.debug("[XTPBin2BinMatrixAgent] Matrix context built (%d chars)", len(self._matrix_context))
        return df

    @staticmethod
    def _build_context(df: pd.DataFrame) -> str:
        """Derive counts, totals, diagonal stability, and transition list."""
        buf = io.StringIO()

        total_units = int(df.values.sum())
        row_totals  = df.sum(axis=1)
        col_totals  = df.sum(axis=0)

        buf.write("=== BIN-TO-BIN TRANSITION MATRIX ===\n\n")
        buf.write(df.to_markdown())
        buf.write("\n\n")

        # Row / column totals
        buf.write("=== PROGRAM A BIN TOTALS ===\n")
        for bin_name, count in row_totals.items():
            buf.write(f"  {bin_name}: {count} units\n")

        buf.write("\n=== PROGRAM B BIN TOTALS ===\n")
        for bin_name, count in col_totals.items():
            buf.write(f"  {bin_name}: {count} units\n")

        buf.write(f"\nTotal units in matrix: {total_units}\n\n")

        # Diagonal (stable) population
        diagonal_total = sum(
            df.loc[r, c]
            for r in df.index
            for c in df.columns
            if r.split("_")[0:2] == c.split("_")[0:2]  # match leading SB_NNNN
            and r in df.columns  # square overlap
        )
        # Simpler: match by exact label equality where both axes share labels
        shared_bins = [b for b in df.index if b in df.columns]
        stable_count = sum(int(df.loc[b, b]) for b in shared_bins)
        stability_pct = 100.0 * stable_count / total_units if total_units else 0.0

        buf.write(f"=== DIAGONAL STABILITY: {stable_count}/{total_units} ({stability_pct:.1f}%) ===\n")
        for b in shared_bins:
            n   = int(df.loc[b, b])
            tot = int(row_totals[b])
            pct = 100.0 * n / tot if tot else 0.0
            buf.write(f"  {b}: {n}/{tot} retained ({pct:.1f}%)\n")

        buf.write("\n=== OFF-DIAGONAL TRANSITIONS ===\n")
        for prog_a_bin in df.index:
            for prog_b_bin in df.columns:
                if prog_a_bin == prog_b_bin:
                    continue
                count = int(df.loc[prog_a_bin, prog_b_bin])
                if count == 0:
                    continue
                src_total = int(row_totals[prog_a_bin])
                pct = 100.0 * count / src_total if src_total else 0.0
                buf.write(
                    f"  {prog_a_bin} -> {prog_b_bin}: {count} units ({pct:.1f}% of Prog A {prog_a_bin})\n"
                )

        return buf.getvalue()

    # ------------------------------------------------------------------
    # Invocation
    # ------------------------------------------------------------------

    def invoke(self, message: str) -> str:
        """Run the agent with *message* and return the answer string.

        The matrix summary (if loaded) is automatically embedded in the
        user message so the LLM has immediate access without needing a
        tool call for basic context.
        """
        self._log._logger.info("[XTPBin2BinMatrixAgent] Invoking agent...")
        if self._matrix_context:
            full_message = (
                f"{message}\n\n"
                f"--- MATRIX DATA ---\n{self._matrix_context}"
            )
        else:
            full_message = message

        result = self._agent.invoke({"messages": [{"role": "user", "content": full_message}]})
        return result["messages"][-1].content

    def analyse(self, csv_path: str) -> str:
        """Load *csv_path* and run the full analysis in one call.

        Returns the agent's Markdown report string.
        """
        self.load_matrix(csv_path)
        return self.invoke(
            "Perform a complete Bin-to-Bin transition analysis following all six "
            "analysis directives in your system prompt.  Identify the main sources "
            "of possible program changes that may have induced the observed bin "
            "shifts and provide actionable recommendations."
        )


# ---------------------------------------------------------------------------
# Script entry-point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    _logger = AgentLogger(name="xtp_bin2bin_agent", level="DEBUG")
    agent   = XTPBin2BinMatrixAgent(logger=_logger)

    report = agent.analyse(r"Programas/Bin2Bin_Matrix.csv")
    print(report)
